
b3_3@sirius-NUC13ANHi5:~/tanaka$ python3 0228_cb.py 
Traceback (most recent call last):
  File "/home/b3_3/tanaka/0228_cb.py", line 4, in <module>
    bot = ChatBot("チャットボット試作版")
  File "/home/b3_3/.local/lib/python3.10/site-packages/chatterbot/chatterbot.py", line 35, in __init__
    self.tagger = Tagger(language=kwargs.get(
  File "/home/b3_3/.local/lib/python3.10/site-packages/chatterbot/tagging.py", line 53, in __init__
    self.nlp = spacy.load(model, exclude=['ner'])
  File "/home/b3_3/.local/lib/python3.10/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/home/b3_3/.local/lib/python3.10/site-packages/spacy/util.py", line 472, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
